### ISSUE TITLE
We want to win constellation hackathon 2023

### ISSUE THREAD

**Issue by rayneh** [rayneh/tardigrade#1]
## Task Assignment 

TODO list and resources for constellation hackathon

## Objective 

Win the most prizes :tada: 

## Task Requirements

ai generated beings ( like each ecosystem has a mascot, for gnosis it is the owl or the word gnosis could be used somehow, for avalanche you have this red yeti or a cold and freezing environment, this could be done for any environment) as dNFTs that evolve everytime they get traded.

### Additional Ideas

Dynamic Storytelling: Each transfer could unveil a new chapter of a story, making each NFT a "living" tale.

Evolutionary Traits: Similar to digital pet games, each NFT could "evolve" acquiring new traits with each transfer.

Generative Art: Use AI to generate art that evolves based on previous images, creating a visual "ancestry" for the NFT.

Token Gated Experiences: Owners could access specific online or real-world experiences, changing with each transfer.

Community Voting: Allow the community to vote on potential outcomes for the NFT's next transformation using a DAO.

Multi-Chain Lore: If bridged to a new chain, the NFT could adapt to the "culture" or "environment" of that chain.

## ToDo

- [x] create team on devpost
- [x] create architecture
- [ ] get team members (dNFT, AI) - 2 spots remain
- [x] setup clusters
- [x] create docker image for pipeline runner
  - [x] install pre-commit 
- [x] get testnet funds
  - [x] polygon
  - [x] ethereum
  - [x] avalanche
  - [x] moonbeam
- [ ] create repos
  - [x] ai image generator, evolver
  - [x] frontend
  - [x] backend
  - [x] middleware to chain
  - [x] common-config
  - [x] renovate

## Improvements

- [ ] fix dependency detection for playbook (renovate)
- [ ] add semantic release and linting (.pre-commit)
- [ ] implement common-config
- [ ] implement mkdocs
- [ ] monitoring

## Resources

- [Devpost](https://constellation-hackathon.devpost.com/)
- [Constellation Registration](https://chain.link/hackathon)
- [Gear Up for Constellation Video](https://www.youtube.com/watch?v=Qhj_SQYaMEw)

## Judging Criteria

- UI/UX/DX
- Originality
- Technicality
- Practicality
- Wow Factor
